//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCKutuphane.Models.EntityF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Duyurular
    {
        public int Id { get; set; }
        public string Kategori { get; set; }
        public string Duyuru { get; set; }
        public Nullable<bool> Durum { get; set; }
    }
}
